services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./scripts:/home/user/scripts:ro
      - ../..:/home/user/test_ws/src/matlogger2:ro
    entrypoint: /bin/bash
    tty: true
    stdin_open: true
    environment:
      - TERM=xterm-256color
      - FOREST_JOBS