name: Build and Test (Noble-ROS2)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image and start the container
      run: docker compose up -d
      working-directory: ./docker/noble-ros2 
    - name: Compile the library
      run: docker compose exec dev ./scripts/build.bash
      working-directory: ./docker/noble-ros2
    - name: Run tests
      run: docker compose exec dev ./scripts/test.bash
      working-directory: ./docker/noble-ros2