shallow_clone: false
branches:
  only:
    - master

platform:
  # - x86
  - x64

configuration:
  # - Debug
  - Release

image:
  - Visual Studio 2015
  # - Visual Studio 2017

cache:
  - C:\cmake-3.10.1-win64-x64

environment:
  global:
      PYTHON: "C:\\conda"
  matrix:
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"


skip_commits:
# Add [av skip] to commit messages
  message: /\[av skip\]/

# # To allow remote connection to appveyor
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - mkdir c:\xx
  - cd c:\xx

  ############################################################################
  # Install Conda
  ############################################################################
  - "git clone --depth 1 git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  ############################################################################
  # Install CMake
  ############################################################################
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.10.1-win64-x64\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.10/cmake-3.10.1-win64-x64.zip'
        7z x -y cmake-3.10.1-win64-x64.zip -oC:\
      }
      $env:PATH="C:\cmake-3.10.1-win64-x64\bin;$env:PATH"

  ############################################################################
  # Install Conda
  ############################################################################
  - conda config --add channels conda-forge
  - conda install hdf5

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmd: git submodule -q update --init
  - ps: |
      mkdir build
      cd build
  - ps: $env:hdf5_dir='C:\conda\Library\'
  - ps: $env:CMAKE_PREFIX_PATH='C:\conda\Library\cmake'
  - cmake -G "Visual Studio 14 2015 Win64" ..


build_script:
  - cmake --build . --config %CONFIGURATION%
  - cpack -C Release

# test_script:
#   - cmd: ctest -v .

on_success:
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\build\libmatio-1.5.11-Win64.tar.gz

deploy: off

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
