language:
  - cpp

cache:
  ccache: true
  directories:
    - $HOME/downloads

addons:
  apt:
    packages:
    - hdf5-tools
    - libhdf5-dev
    - hdf5-helpers

matrix:
  include:
    - os: linux
    - os: osx

branches:
  only:
  - master

before_install:
  # Travis machines have 2 cores
  - JOBS=2

  ############################################################################
  # Handle caching of downloaded files
  ############################################################################
  - export DL_DIR=$HOME/downloads
  - curl -fsSkL https://raw.githubusercontent.com/openmeeg/ci-utils/master/travis/travis_tools.sh > x.sh && source ./x.sh

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - CMAKE_VERSION=3.10.1
  - curl -fsSkL https://raw.githubusercontent.com/openmeeg/ci-utils/master/travis/install_cmake.sh > x.sh && source ./x.sh

  ############################################################################
  # Install HDF5
  ############################################################################
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        rm -rf /usr/local/include/c++;
        brew install hdf5;
    fi


script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo $LD_LIBRARY_PATH; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then echo $DYLD_LIBRARY_PATH; fi
  - echo "cmake .. ${CMAKE_OPTIONS}"
  - cmake .. ${CMAKE_OPTIONS}
  - cmake --build .
  # - ctest -v .

after_success:

notifications:
  email: false
